(()=>{'use strict';
const KEYSETS={major:[{tonic:'C',scale:['C','D','E','F','G','A','B']},{tonic:'G',scale:['G','A','B','C','D','E','F#']},{tonic:'D',scale:['D','E','F#','G','A','B','C#']},{tonic:'A',scale:['A','B','C#','D','E','F#','G#']},{tonic:'E',scale:['E','F#','G#','A','B','C#','D#']},{tonic:'B',scale:['B','C#','D#','E','F#','G#','A#']},{tonic:'F#',scale:['F#','G#','A#','B','C#','D#','E#']},{tonic:'Db',scale:['Db','Eb','F','Gb','Ab','Bb','C']},{tonic:'Ab',scale:['Ab','Bb','C','Db','Eb','F','G']},{tonic:'Eb',scale:['Eb','F','G','Ab','Bb','C','D']},{tonic:'Bb',scale:['Bb','C','D','Eb','F','G','A']},{tonic:'F',scale:['F','G','A','Bb','C','D','E']}],minor:[{tonic:'C',scale:['C','D','Eb','F','G','Ab','Bb']},{tonic:'G',scale:['G','A','Bb','C','D','Eb','F']},{tonic:'D',scale:['D','E','F','G','A','Bb','C']},{tonic:'A',scale:['A','B','C','D','E','F','G']},{tonic:'E',scale:['E','F#','G','A','B','C','D']},{tonic:'B',scale:['B','C#','D','E','F#','G','A']},{tonic:'F#',scale:['F#','G#','A','B','C#','D','E']},{tonic:'C#',scale:['C#','D#','E','F#','G#','A','B']},{tonic:'G#',scale:['G#','A#','B','C#','D#','E','F#']},{tonic:'Eb',scale:['Eb','F','Gb','Ab','Bb','Cb','Db']},{tonic:'Bb',scale:['Bb','C','Db','Eb','F','Gb','Ab']},{tonic:'F',scale:['F','G','Ab','Bb','C','Db','Eb']}]};
const MODES={major:{qualities:['major','minor','minor','major','major','minor','diminished'],degrees:['I','ii','iii','IV','V','vi','vii°'],functions:['Tónica','Supertónica','Mediante','Subdominante','Dominante','Superdominante','Sensible'],label:'mayor',eyebrow:'Escala natural mayor',pattern:'<strong>Patrón fijo:</strong> I, IV y V son mayores; ii, iii y vi son menores; vii° es disminuido.'},minor:{qualities:['minor','diminished','major','minor','minor','major','major'],degrees:['i','ii°','III','iv','v','VI','VII'],functions:['Tónica','Supertónica','Mediante','Subdominante','Dominante menor','Submediante','Subtónica'],label:'menor natural',eyebrow:'Escala menor natural',pattern:'<strong>Patrón fijo:</strong> i, iv y v son menores; III, VI y VII son mayores; ii° es disminuido.'}};
const PC={C:0,'C#':1,Db:1,D:2,'D#':3,Eb:3,E:4,Fb:4,'E#':5,F:5,'F#':6,Gb:6,G:7,'G#':8,Ab:8,A:9,'A#':10,Bb:10,B:11,Cb:11},SHARP=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'],FLAT=['C','Db','D','Eb','E','F','Gb','G','Ab','A','Bb','B'],LATIN={C:'DO',D:'RE',E:'MI',F:'FA',G:'SOL',A:'LA',B:'SI'};
const state={mode:'major',keyIndex:0,nomenclature:'latin',instrument:'guitar',selectedDegree:0,inversion:0,theme:localStorage.getItem('circulos-theme')||'system'};
const el=Object.fromEntries(['toneSelector','scaleEyebrow','scaleTitle','scalePattern','chordsTitle','diatonicGrid','selectedDegreeLabel','selectedChordTitle','selectedChordNotes','pianoKeyboard','pianoVoicingText','pianoPanel','guitarPanel','statusKey','statusChord','statusPosition','themeBtn','toast'].map(id=>[id,document.getElementById(id)]));
const keys=()=>KEYSETS[state.mode],mode=()=>MODES[state.mode],key=()=>keys()[state.keyIndex],notePc=n=>PC[n],selectedChord=()=>buildChords()[state.selectedDegree];
const formatNote=n=>state.nomenclature==='english'?n.replace('#','♯').replace('b','♭'):`${LATIN[n[0]]||n[0]}${n.slice(1).replace('#','♯').replace('b','♭')}`;const qualityLabel=q=>q==='major'?'Mayor':q==='minor'?'Menor':'Disminuido';const chordSymbol=c=>c.quality==='minor'?`${formatNote(c.root)}m`:c.quality==='diminished'?`${formatNote(c.root)}°`:formatNote(c.root);const chordLongName=c=>`${formatNote(c.root)} ${qualityLabel(c.quality).toLowerCase()}`;const chordIntervals=q=>q==='major'?[0,4,7]:q==='minor'?[0,3,7]:[0,3,6];const chromaticName=(pc,flat=false)=>(flat?FLAT:SHARP)[(pc+12)%12];
function buildChords(){const k=key(),m=mode();return k.scale.map((root,i)=>({root,rootPc:notePc(root),quality:m.qualities[i],degree:m.degrees[i],functionName:m.functions[i],notes:[k.scale[i],k.scale[(i+2)%7],k.scale[(i+4)%7]]}))}
function renderToneSelector(){el.toneSelector.innerHTML=keys().map((k,i)=>`<button class="tone-btn ${i===state.keyIndex?'active':''}" data-k="${i}" type="button">${formatNote(k.tonic)}</button>`).join('');el.toneSelector.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.keyIndex=Number(b.dataset.k);state.selectedDegree=state.inversion=0;renderAll()})}
function renderScale(){el.scaleEyebrow.textContent=mode().eyebrow;el.scaleTitle.textContent=`Escala de ${formatNote(key().tonic)} ${mode().label}`;el.scalePattern.innerHTML=mode().pattern}
function renderChords(){const chords=buildChords();el.chordsTitle.textContent=`Los 7 acordes de ${formatNote(key().tonic)} ${mode().label}`;el.diatonicGrid.innerHTML=chords.map((c,i)=>`<button class="chord-card ${i===state.selectedDegree?'active':''}" data-d="${i}" type="button"><span class="badge">${c.degree}</span><strong class="chord-name">${chordSymbol(c)}</strong><span class="chord-quality">${qualityLabel(c.quality)}</span><span class="chord-function">${c.functionName}</span><span class="chord-notes">${c.notes.map(formatNote).join(' · ')}</span></button>`).join('');el.diatonicGrid.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.selectedDegree=Number(b.dataset.d);state.inversion=0;renderAll()})}
function pianoVoicingMidi(ch,inversion=state.inversion){const notes=chordIntervals(ch.quality).map(i=>60+ch.rootPc+i);while(notes[0]>=72)notes.forEach((_,i)=>notes[i]-=12);for(let i=0;i<inversion;i++)notes.push(notes.shift()+12);return notes}
function buildPiano(){const ch=selectedChord(),voicing=pianoVoicingMidi(ch),voicingSet=new Set(voicing),chordPcs=new Set(ch.notes.map(notePc)),rootPc=ch.rootPc,whitePcs=new Set([0,2,4,5,7,9,11]),labels=state.nomenclature==='latin'?['DO','DO♯','RE','RE♯','MI','FA','FA♯','SOL','SOL♯','LA','LA♯','SI']:['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'];const start=48,end=84,whites=[];for(let midi=start;midi<=end;midi++)if(whitePcs.has(midi%12))whites.push(midi);const w=cssPx('--key-w',58),pad=parseFloat(getComputedStyle(el.pianoKeyboard).paddingLeft)||0;el.pianoKeyboard.innerHTML='';whites.forEach((midi,index)=>{const pc=midi%12,keyBtn=document.createElement('span');keyBtn.className=`white-key${chordPcs.has(pc)?' chord-tone':''}${voicingSet.has(midi)?' voicing-tone':''}${pc===rootPc?' root-tone':''}`;keyBtn.textContent=labels[pc];el.pianoKeyboard.appendChild(keyBtn);if([0,2,5,7,9].includes(pc)&&midi+1<=end){const bm=midi+1,bpc=bm%12,black=document.createElement('span');black.className=`black-key${chordPcs.has(bpc)?' chord-tone':''}${voicingSet.has(bm)?' voicing-tone':''}${bpc===rootPc?' root-tone':''}`;black.style.left=`${pad+(index+1)*w}px`;black.textContent=labels[bpc];el.pianoKeyboard.appendChild(black)}});el.pianoKeyboard.style.minWidth=`${whites.length*w+8}px`;el.pianoVoicingText.textContent=voicing.map(m=>formatNote(chromaticName(m%12,key().tonic.includes('b')))).join(' · ');document.querySelectorAll('[data-inversion]').forEach(btn=>btn.classList.toggle('active',Number(btn.dataset.inversion)===state.inversion))}
function renderGuitar(){window.circulosChord={name:chordLongName(selectedChord()),rootPc:selectedChord().rootPc,quality:selectedChord().quality};document.dispatchEvent(new CustomEvent('circulos:chord'))}
function renderSelectedChord(){const ch=selectedChord();el.selectedDegreeLabel.textContent=`Grado ${ch.degree} · ${ch.functionName}`;el.selectedChordTitle.textContent=chordLongName(ch);el.selectedChordNotes.textContent=`Notas: ${ch.notes.map(formatNote).join(' · ')}`;buildPiano();renderGuitar()}
function setInstrument(inst){state.instrument=inst==='piano'?'piano':'guitar';document.querySelectorAll('[data-instrument]').forEach(btn=>btn.classList.toggle('active',btn.dataset.instrument===state.instrument));el.pianoPanel.classList.toggle('hidden',state.instrument!=='piano');el.guitarPanel.classList.toggle('hidden',state.instrument!=='guitar');updateStatus()}
function updateStatus(){const ch=selectedChord();el.statusKey.textContent=`${formatNote(key().tonic)} ${mode().label}`;el.statusChord.textContent=chordLongName(ch);el.statusPosition.textContent=state.instrument==='piano'?['Fundamental','1.ª inversión','2.ª inversión'][state.inversion]:'Guitarra'}
function cssPx(name,fallback){const raw=getComputedStyle(document.documentElement).getPropertyValue(name).trim(),value=parseFloat(raw);return Number.isFinite(value)&&value>0?value:fallback}
function applyTheme(){const resolved=state.theme==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):state.theme;document.documentElement.dataset.theme=resolved;document.querySelector('meta[name="theme-color"]').setAttribute('content',resolved==='dark'?'#101110':'#f5f5f2')}
function cycleTheme(){state.theme=state.theme==='system'?'light':state.theme==='light'?'dark':'system';localStorage.setItem('circulos-theme',state.theme);applyTheme();showToast(`Apariencia: ${state.theme==='system'?'sistema':state.theme==='light'?'clara':'oscura'}`)}
function showToast(msg){if(!el.toast)return;el.toast.textContent=msg;el.toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>el.toast.classList.remove('show'),1900)}
function renderAll(){renderToneSelector();renderScale();renderChords();renderSelectedChord();setInstrument(state.instrument);updateStatus()}
document.querySelectorAll('[data-nomenclature]').forEach(btn=>btn.addEventListener('click',()=>{state.nomenclature=btn.dataset.nomenclature;document.querySelectorAll('[data-nomenclature]').forEach(i=>i.classList.toggle('active',i===btn));renderAll()}));document.querySelectorAll('[data-mode]').forEach(btn=>btn.addEventListener('click',()=>{state.mode=btn.dataset.mode;state.keyIndex=0;state.selectedDegree=0;state.inversion=0;document.querySelectorAll('[data-mode]').forEach(i=>i.classList.toggle('active',i===btn));renderAll()}));document.querySelectorAll('[data-instrument]').forEach(btn=>btn.addEventListener('click',()=>setInstrument(btn.dataset.instrument)));document.querySelectorAll('[data-inversion]').forEach(btn=>btn.addEventListener('click',()=>{state.inversion=Number(btn.dataset.inversion);buildPiano();updateStatus()}));document.querySelectorAll('.nav-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav-btn').forEach(i=>i.classList.remove('active'));btn.classList.add('active');document.getElementById(btn.dataset.target)?.scrollIntoView({behavior:'smooth',block:'start'})}));document.getElementById('scrollTopBtn')?.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));el.themeBtn?.addEventListener('click',cycleTheme);matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',()=>{if(state.theme==='system')applyTheme()});applyTheme();renderAll();})();